// This file is autogenerated by drizzle/commands/seed-generate-mock.ts
// Do not edit this file directly.

import { NewTemplate } from '@/drizzle/schema/templates'

export const seed: NewTemplate[] = [
    {
        name: ".gitconfig",
        description: undefined,
        type: "null",
        file: "registry/.gitconfig",
    },
    {
        name: "key-manager.sh",
        description: undefined,
        type: "application/x-sh",
        file: "registry/.ssh/key-manager.sh",
    },
];