// This file is autogenerated by drizzle/commands/seed-generate-mock.ts
// Do not edit this file directly.

import { NewTemplate } from '@/drizzle/schema/templates'

export const seed: NewTemplate[] = [
   {
        name: "README",
        extension: ".md",
        description: undefined,
        type: "text/markdown",
        file: "registry/README.md",
    },   {
        name: "test",
        extension: ".sh",
        description: undefined,
        type: "application/x-sh",
        file: "registry/test.sh",
    },
];